name: TokenFrontEnd
main: me.smithey.can.code.RapidFireMC
version: 1.0
description: Tokens Frontend User Interface Plugin
author: Smithey
commands:
    Arcade:
        description: Main Arcade Command
    Tokens:
        description: Tokens Command